language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get install cmake g++ pkg-config jq
  - sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
  - cargo install cargo-kcov
  - cargo kcov --print-install-kcov-sh | sh

script:
  - cargo check --all-features
  - cargo test --verbose -- --nocapture

after_success:
  - cargo kcov --coveralls
